### ISSUE TITLE
[BUG] Garbo doesn't recognize digitized Embezzler when delay expires, but fight with embezzler is in progress

### ISSUE THREAD

**Issue by Jongberry** [loathers/garbage-collector#1846] opened 2024-04-11 15:46 UTC
**Describe the bug**
Garbo does not recognize digitized embezzlers once the delay expires.  The script gives the error pasted below. When this happens and I go to the relay browser, I am in the middle of a fight with the digitized embezzler. I'm not 100% certain this happens for every digitized embezzler, but it happens at least for most. It happens every day I use garbo, approx. 5 times per 400-500 turn session.

> JavaScript exception: KoLmafia error: You're on your own, partner. (Macro Aborted ("abort "Expected a digitized Knob Goblin Embezzler, but encountered something else.""))
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:29435 (_do)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:29236 (execute)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48155 (execute)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:29156 (run)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48212 (runGarboTasks)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48218 (runGarboQuests)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48682
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:40397 (withClan)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:40391 (withVIPClan)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48653
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:40376 (withStash)
> at file:/C:/Users/12168/OneDrive/Desktop/scripts/garbage-collector/garbo.js:48652 (main)

[Jongx_20240411.txt](https://github.com/loathers/garbage-collector/files/14948345/Jongx_20240411.txt)

Thank you.

**Comment by horrible-little-slime** [comment] 2024-04-11 22:40
Duplicate of #1824

**Closed by horrible-little-slime** 2024-04-11 22:40 UTC
