### ISSUE TITLE
[BUG] CCS aborts on romantic monster fight

### ISSUE THREAD

**Issue by BringDaRufus** [loathers/garbage-collector#1914] opened 2024-06-04 05:58 UTC
This happens on each encounter with embezzlers who are shot with a [badly romantic arrow](https://kol.coldfront.net/thekolwiki/index.php/Fire_a_badly_romantic_arrow).

Turn:

```

Executing Barf Turn/Barf  
Choosing to use Li'l Xenomorph (expected value of 2186.5 from familiar drops, 0.0 from familiar abilities and 1011.8 from outfit) over Jill-of-All-Trades (expected value of 112.0 from familiar drops, 663.1 from familiar abilities and 759.9 from outfit).  
  
Visit to Dinseylandfill: Barf Mountain in progress…  
(Romantic Monster window begin counter expired)  
  
[279] Barf Mountain  
Preference lastEncounter changed from This Ride Is Like… A Rollercoaster Baby Baby to Knob Goblin Embezzler  
Encounter: Knob Goblin Embezzler  
Preference _romanticFightsLeft changed from 1 to 0  
Preference relayCounters changed from 278:Romantic Monster window begin loc=*:lparen.gif:288:Romantic Monster window end loc=* type=wander:rparen.gif to 288:Romantic Monster window end loc=* type=wander:rparen.gif  
Preference relayCounters changed from 288:Romantic Monster window end loc=* type=wander:rparen.gif to  
Preference romanticTarget changed from Knob Goblin Embezzler to  
Round 0: player wins initiative!  
Preference cosmicBowlingBallReturnCombats changed from 22 to 21  
Round 1: Your toy train moves ahead to the Meat Mine Sluice. It's twice as effective because your train just visited the coal hopper. The sluice opens and pours out some meat!  
Preference trainsetPosition changed from 161 to 162  
You gain 1,710 Meat.  
Round 1: player executes a macro!  
KoLmafia thinks it is round 2 but KoL thinks it is round 1  
You're on your own, partner. (Macro Aborted ("abort"))  
[Click here to continue in the relay browser.](main.php)  
  
  
Preference _concoctionDatabaseRefreshes changed from 540 to 541  
hpAutoRecoveryTarget => 0  
Preference hpAutoRecoveryTarget changed from 0.0 to 0  
mpAutoRecoveryTarget => 0  
Preference mpAutoRecoveryTarget changed from 0.0 to 0  
Preference customCombatScript changed from grimoire_macro to wham  
CCS set to wham  
Autoattack is disabled.  
Autoattack is disabled.  
No spading data has been collected yet. Please try again later.  
logPreferenceChange => false  
Preference logPreferenceChange changed from true to false  
CCS set to wham  
(but battle action is currently set to attack with weapon)  
dontStopForCounters => false  
hpAutoRecoveryTarget => 1  
mpAutoRecoveryTarget => 0.3  
allowNonMoodBurning => true  
valueOfInventory => 1.8  
spadingScript =>  
choiceAdventure1106 => 0  
choiceAdventure1107 => 0  
choiceAdventure1340 => 0  
choiceAdventure1341 => 0  
choiceAdventure1467 => 0  
choiceAdventure1468 => 0  
choiceAdventure1469 => 0  
choiceAdventure1470 => 0  
choiceAdventure1471 => 0  
choiceAdventure1472 => 0  
choiceAdventure1473 => 0  
choiceAdventure1474 => 0  
choiceAdventure1475 => 0  
choiceAdventure1324 => 0  
Encounter: Knob Goblin Embezzler  
You fought 9 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!  
Including this, you have fought 118 across all ascensions today  
Extreme Items:  
1 transporter transponder worth 8549 total  
1 flapper fly worth 6183 total  
14 sleaze nuggets worth 3767 total  
2 mimic egg worth 0 total  
1 yellow candy heart worth 5 total  
1 crunchy brush worth 10 total  
This run of garbo, across 14 turns you generated 93,355 meat, with 67,873 raw meat and 25,482 from items  
So far today, across 607 turns you generated 4,549,118 meat, with 3,258,841 raw meat and 1,290,277 from items  
You are currently in a fight.  
Warning: Insufficient turns were run, so this estimate is subject to large variance. Be careful when using these values as is.  
Marginal MPA: NaN [raw] + NaN [items] = NaN [total]  
JavaScript exception: KoLmafia error: You're on your own, partner. (Macro Aborted ("abort"))  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:30108 (_do)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:29909 (execute)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49395 (execute)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:29829 (run)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49452 (runGarboTasks)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49458 (runGarboQuests)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49922  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:41352 (withClan)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:41346 (withVIPClan)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49893  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:41331 (withStash)  
at file:/Users/player/Library/Application%20Support/KoLmafia/scripts/garbage-collector/garbo.js:49892 (main)
```

I'm not familiar with garbo's setup, managed to track it down to [here](https://github.com/loathers/garbage-collector/blob/e710337dce599311389a94b2d42e4bd2afeeecd4/packages/garbo/src/tasks/barfTurn.ts#L840), where the fight proceeds fine if I remove the `&& !gotjump` from there. I doubt that's the correct fix though.

**Comment by horrible-little-slime** [comment] 2024-06-04 14:57
Duplicate of #1824

**Closed by horrible-little-slime** 2024-06-04 14:57 UTC
