### ISSUE TITLE
[BUG] Daylight savings bug? 

### ISSUE THREAD

**Issue by NoctiBeard** [loathers/garbage-collector#1720] opened 2023-11-09 04:44 UTC
Also, read [this](BUGS.md).

**Describe the bug**
JavaScript exception: Error: Eep! It's a mere 82128 seconds until rollover!

**To Reproduce**

Run garbo

**Comment by ckrentz** [comment] 2023-11-09 07:18
Having this issue as well. Updated Mafia, updated Garbo, tried restarting and clearing settings. Seems completely inoperable at the moment.

**Comment by horrible-little-slime** [comment] 2023-11-09 19:24
Duplicate of #1721

**Closed by horrible-little-slime** 2023-11-09 19:24 UTC
