### ISSUE TITLE
[BUG] Wandering Dia Monsters Abort Garbo In Some Cases

### ISSUE THREAD

**Issue by tsuyoshikentsu** [loathers/garbage-collector#1826] opened 2024-03-15 21:19 UTC
**Describe the bug**

Encountering a Dia wandering monster in Barf is causing garbo to abort.

**To Reproduce**

Nothing, besides running the script.

**Expected behavior**
Garbo would handle the combat without user intervention.

**Session Log**
[ahdar_musicstopper_20240315.txt](https://github.com/loathers/garbage-collector/files/14620860/ahdar_musicstopper_20240315.txt)

Aborts occurred on the following adventures:

Pre-Loop
264
291
323
350
375
410
439
466
496
522
556
589
617
647
674
705

Post-Loop
275
310

This redtext is taken from adventure 275 post-loop, but is the same as all of the other occurrences:

Round 1: ahdar musicstopper executes a macro!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner. (Macro Aborted ("abort"))
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)

Then, post preference changes and garbo summary:

JavaScript exception: KoLmafia error: You're on your own, partner. (Macro Aborted ("abort"))
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:29435 (_do)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:29236 (execute)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48091 (execute)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:29156 (run)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48148 (runGarboTasks)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48154 (runGarboQuests)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48617
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:40384 (withClan)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:40378 (withVIPClan)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48588
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:40363 (withStash)
at file:/C:/Users/tsuyoshikentsu/Downloads/KoLMafia/scripts/garbage-collector/garbo.js:48587 (main)

**Additional context**
This happened pre- and post-loop.

**Comment by farmstall** [comment] 2024-03-16 01:40
I am also having this issue. I thought it was maybe the Monster Manuel interacting poorly, but I have all 4 wanderers Manueled at least once.

**Comment by tsuyoshikentsu** [comment] 2024-03-17 02:30
As an additional data point, I do not have a Monster Manuel.

**Comment by horrible-little-slime** [comment] 2024-03-18 03:32
Autoattack appears not to be triggering against bosses/special monsters despite checking the aabosses flag

**Comment by horrible-little-slime** [comment] 2024-03-27 01:54
The issue seems to be that garbo is failing to set the aabosses flag under certain circumstances. For now, you can fix this by enabling "use autoattack against bosses and special monster" under account options. I'm now closing this ticket not because the issue is solved, but because equipped with this knowledge I am confident it is a duplicate of #1824

**Closed by horrible-little-slime** 2024-03-27 01:54 UTC
