### ISSUE TITLE
Garbo crashing out on kge [BUG]

### ISSUE THREAD

**Issue by Minkseru** [loathers/garbage-collector#1852] opened 2024-04-18 15:00 UTC
[akira_the_noob_20240418.txt](https://github.com/loathers/garbage-collector/files/15026687/akira_the_noob_20240418.txt)

It keeps crashing on [I think} digitized copies of Knob Goblin Embezzler.
It will say stuff like " Expected digitized knob goblin embezzler, but encounterered something else.  yet when I go to relay to finish teh combat it is ALWAYS KGE.

**To Reproduce**
I have just typed Garbo and let it do it's thing.  Your guess is honestly as good as mine as to what is crashing it at that point.

1. Go to '...'CLi
2. Click on '....'type Garbo

**Expected behavior**
I expected it to keep running instead of getting stuck on the random numbered kge fight.

**Session Log**
Attach a full KoLMafia session log from the day you encountered the bug. Include details about when in the log the bug occurred to help developers rapidly find the error. Copy and paste any associated red text printed to the gCLI during this error.

**Additional context**
Add any other context about the problem here. Does this always happen post-loop, but never pre-loop? Did this start happening when you got some particular IotM?
It I think is happening during digitize?
I did update kolmafia and garbo before trying to run it after it told me to update.

**Comment by Minkseru** [comment] 2024-04-20 06:11
[akira_the_noob_20240417.txt](https://github.com/loathers/garbage-collector/files/15047031/akira_the_noob_20240417.txt)
[akira_the_noob_20240418.txt](https://github.com/loathers/garbage-collector/files/15047032/akira_the_noob_20240418.txt)
[akira_the_noob_20240419.txt](https://github.com/loathers/garbage-collector/files/15047033/akira_the_noob_20240419.txt)
There are several instances in each where it crases stating that it wants a knob goblin embezzler, and freaking out because it think it is not a knob goblin embezzler.
The one in the OP had this instance at the bottom

**Comment by Minkseru** [comment] 2024-04-20 06:14
![image](https://github.com/loathers/garbage-collector/assets/167432083/67c2dc6b-6cef-4ab4-a421-3d16157ecc36)
![image](https://github.com/loathers/garbage-collector/assets/167432083/1e3853fc-f43f-4c14-895d-77691e71c8d2)

**Comment by horrible-little-slime** [comment] 2024-04-23 02:25
duplicate of #1824

**Closed by horrible-little-slime** 2024-04-23 02:25 UTC

**Comment by eric-the-redbeard** [comment] 2024-04-24 20:14
I am also getting the 2nd vs 1st turn issue, but with wandering (wink from reanimated reanimator) versions of KGE. I enter the fight, finish it, and then restart garbo. Once all 3 wanderers are vanquished, the script finishes without further interruption.

What should I do? Log text below...

[2134] Barf Mountain
Preference lastEncounter changed from horrible tourist family to Knob Goblin Embezzler
Encounter: Knob Goblin Embezzler
Preference _romanticFightsLeft changed from 3 to 2
Preference relayCounters changed from 2135:Romantic Monster window end loc=* type=wander:rparen.gif to
Preference relayCounters changed from to 2148:Romantic Monster window begin loc=*:lparen.gif
Preference relayCounters changed from 2148:Romantic Monster window begin loc=*:lparen.gif to 2148:Romantic Monster window begin loc=*:lparen.gif:2158:Romantic Monster window end loc=* type=wander:rparen.gif
Round 0: hastiferarken wins initiative!
Preference cosmicBowlingBallReturnCombats changed from 18 to 17
Round 1: Your toy train moves ahead to the Coal Hopper. Your train takes on coal to power the next stop.
Preference trainsetPosition changed from 2367 to 2368
Round 1: hastiferarken executes a macro!
KoLmafia thinks it is round 2 but KoL thinks it is round 1
You're on your own, partner. (Macro Aborted ("abort"))
[Click here to continue in the relay browser.](https://github.com/loathers/garbage-collector/issues/main.php)


logPreferenceChangeFilter => garboEmbezzlerCount,garboEmbezzlerDate,garboEmbezzlerSources,libram_savedMacro,maximizerMRUList,spadingData,testudinalTeachings
Preference logPreferenceChangeFilter changed from _lastCombatStarted,libram_savedMacro,maximizerMRUList,testudinalTeachings to garboEmbezzlerCount,garboEmbezzlerDate,garboEmbezzlerSources,libram_savedMacro,maximizerMRUList,spadingData,testudinalTeachings
hpAutoRecoveryTarget => 0
Preference hpAutoRecoveryTarget changed from 0.0 to 0
mpAutoRecoveryTarget => 0
Preference mpAutoRecoveryTarget changed from 0.0 to 0
allowNonMoodBurning => true
Preference allowNonMoodBurning changed from false to true
Preference customCombatScript changed from grimoire_macro to garbo
CCS set to garbo
Autoattack is disabled.
Autoattack is disabled.
No spading data has been collected yet. Please try again later.
logPreferenceChangeFilter =>
Preference logPreferenceChangeFilter changed from garboEmbezzlerCount,garboEmbezzlerDate,garboEmbezzlerSources,libram_savedMacro,maximizerMRUList,spadingData,testudinalTeachings to
Preference customCombatScript changed from garbo to default
CCS set to default
autoSatisfyWithMall => false
Preference autoSatisfyWithMall changed from true to false
autoSatisfyWithNPCs => false
Preference autoSatisfyWithNPCs changed from true to false
autoSatisfyWithCoinmasters => false
Preference autoSatisfyWithCoinmasters changed from true to false
dontStopForCounters => false
Preference dontStopForCounters changed from true to false
hpAutoRecoveryTarget => 0.95
Preference hpAutoRecoveryTarget changed from 0.0 to 0.95
mpAutoRecoveryTarget => 0.05
Preference mpAutoRecoveryTarget changed from 0.0 to 0.05
currentMood => default
Preference currentMood changed from apathetic to default
autoTuxedo => false
Preference autoTuxedo changed from true to false
autoPinkyRing => false
Preference autoPinkyRing changed from true to false
autoGarish => false
Preference autoGarish changed from true to false
valueOfInventory => 1.8
Preference valueOfInventory changed from 2.0 to 1.8
spadingScript =>
Preference spadingScript changed from excavator.js to
choiceAdventure1340 => 0
Preference choiceAdventure1340 changed from 1 to 0
choiceAdventure1341 => 0
Preference choiceAdventure1341 changed from 1 to 0
shadowLabyrinthGoal => browser
Preference shadowLabyrinthGoal changed from effects to browser
Encounter: Knob Goblin Embezzler
Preference garboEmbezzlerCount changed from 36 to 55
Preference garboEmbezzlerSources changed from Chateau Painting,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Unknown Source,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,4-d Camera,Combat Lover's Locket,Fax,Unknown Source,Scepter Semirare,Saxophone semirare,Lucky!,Saxophone semirare to Chateau Painting,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Unknown Source,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Habitats Monster,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,Backup,4-d Camera,Combat Lover's Locket,Fax,Unknown Source,Scepter Semirare,Saxophone semirare,Lucky!,Saxophone semirare,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source,Unknown Source
You fought 19 Knob Goblin Embezzler at the beginning of the day, and an additional 0 digitized Knob Goblin Embezzler throughout the day. Good work, probably!
Including this, you have fought 55 across all ascensions today
Extreme Items:
1 Yeast of Boris worth 6966 total
1 crappy waiter disguise worth 6300 total
10 bag of park garbage worth 1872 total
-1 Fudgie Roll worth -179 total
-1 ribbon candy worth -50 total
1 AutumnFest ale worth 10 total
Preference garboResultsMeat changed from 1111465 to 1122230
Preference garboResultsItems changed from 927005 to 945708
Preference garboResultsTurns changed from 34 to 39
This run of garbo, across 5 turns you generated 29,468 meat, with 10,765 raw meat and 18,703 from items
So far today, across 39 turns you generated 2,067,938 meat, with 1,122,230 raw meat and 945,708 from items
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
You are currently in a fight.
Warning: Insufficient turns were run, so this estimate is subject to large variance. Be careful when using these values as is.
Marginal MPA: NaN [raw] + NaN [items] = NaN [total]
JavaScript exception: KoLmafia error: You're on your own, partner. (Macro Aborted ("abort"))
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:29700 (_do)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:29501 (execute)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:48586 (execute)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:29421 (run)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:48643 (runGarboTasks)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:48649 (runGarboQuests)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:49113
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:40757 (withClan)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:40751 (withVIPClan)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:49084
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:40736 (withStash)
at file:/C:/Program%20Files/kolmafia/scripts/garbage-collector/garbo.js:49083 (main)
