### ISSUE TITLE
[ISSUE] Circadian Rhythm only being used pre-Ascension when looping, not used post-ascension despite being available

### ISSUE THREAD

**Issue by Arashmin** [loathers/garbage-collector#2030] opened 2024-08-22 15:30 UTC
**Is your feature request related to a problem? Please describe.**
Somewhat, the change to using cheerless exec mimes in place of embezzlers appears to have impacted how Rhythm is used, resulting in 11 less rollover adventures per session.

**Describe the solution you'd like**
It could help to make the Circadian Rhythm target equal to whatever is the target of our copy farming, in case it changes from exec mime in the future, otherwise changing it to the exec mime should be enough for now

**Describe alternatives and complications**
Having Rhythm target = copy farm target (in case mime changes again) may be arduous to program for the CCS required, though admittedly I'm not sure how the code all works under the hood

Tourists could be used instead but it's hard to get a full 11 of the same phylum in a row without wasting resources; Shadow rift could do it; NEP almost works as a full dude area, would have to chain more dudes after (pygmies?); Ditto on Snojo and constructs (bricko?)

**Additional context**
Thanks muchly for the hard work through these times of change!
EDIT1: This may be more a bug than a feature, see below.  I thought I was missing 11/11 adventures, turns out I'm missing 11/22 adventures from Circadian Rhythm instead.

**Comment by horrible-little-slime** [comment] 2024-08-23 18:40
I'm definitely having it cast twice a day--can you share a session log?

**Comment by Arashmin** [comment] 2024-08-23 21:45
See logs below, for July 30th and today for comparison.

The 'twice a day' hint helped.  In review, my script is not using it for the second leg of the day, after ascending, but does use it before ascending.  So it is gathering 11 of the possible rollover adventures.  I thought it was only giving 11 altogether, not 22.

[Arashmin_20240730.txt](https://github.com/user-attachments/files/16733862/Arashmin_20240730.txt)
[Arashmin_20240823.txt](https://github.com/user-attachments/files/16733868/Arashmin_20240823.txt)

As with all issues that aren't being replicated by all peoples, going to also delete and reinstall the script, see if that helps.

**Comment by horrible-little-slime** [comment] 2024-08-24 01:56
> > You fought 1 cheerless mime executive at the beginning of the day, and an additional 0 digitized cheerless mime executive throughout the day. Good work, probably!
> Including this, you have fought 108 across all ascensions today

That's your EOD log line; closing because it's a duplicate of #2014

**Closed by horrible-little-slime** 2024-08-24 01:56 UTC
