### ISSUE TITLE
[new feature] endOfDay action support for garbo (nightcaps, etc)

### ISSUE THREAD

**Issue by docrostov** [loathers/garbage-collector#745] opened 2022-01-13 21:09 UTC
this is sourced from the #End-of-Day thread within the garbo chat on the discord. this is rooted in the initial idea that we want to move funfund acquisition to the end of the day. as part of that, we want to create a landing spot for "end-of-day" tasks. some initial thoughts on early things we'd like to add to this:

```
- finishGarboBarfDay()
--- map/saber for pills (implemented)
--- get funfunds (implemented)
--- time prank manny
--- overdrink+stooper via garbo diet script
--- get into your pajamas, check if you will have too many rollover advs
--- use adv resolutions if profitable & won't put you over the cap too much
--- run a few overdrunk turns if you go over the 200 cap
--- give the user a kiss on the forehead and tenderly put them to sleep, zzzz
--- output garbo profit tracking
```

a few design fundamentals for this:
- this should be opt in; garbo should not nightcap unless a user has expressed they want this
- we need to delineate between "end of barf day" tasks and "end of actual KOL day" tasks; i still think we encase them in one block but happy to hear counterarguments
- phred wants us to consider EOD turn-taking tasks; things like melf dupes, sparring, grabbing fused fuses, turning in gerald/ine, etc

**Comment by horrible-little-slime** [comment] 2023-11-07 19:51
End of Day tasks exist now! Congrats!

We don't actually nightcap specifically yet though, so I'm not personally closing this!

**Comment by horrible-little-slime** [comment] 2024-03-27 02:03
I actually am going to close this because so much of the body of the issue is devoted to the general functionality. But we do have EOD tasks, we just need to actually add nightcapping.

**Closed by horrible-little-slime** 2024-03-27 02:03 UTC
